server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1010/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    preferIpAddress: true



spring:
  application:
    name: Amazon-Product
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: systems
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: update
